language: r
cache: packages
dist: bionic
os: linux

warnings_are_errors: false

r:
  - release
  - oldrel

bioc_required: true
bioc_packages:
  - phyloseq
  - Biostrings


before_deploy:
  - R -e "install.packages('roxygen2', repos = 'http://cran.rstudio.com')"
  - R -e "staticdocs::build_site(examples = TRUE)"

after_success:
  - Rscript -e 'covr::codecov()'

